#!/usr/bin/env bash
# Build the Coffice LibreOffice extension (Coffice.oxt).
#
# The .oxt is a ZIP. We build it with Python's zipfile so no external `zip`
# binary is required. The build also:
#   * copies the hosting contract + document-command logic from
#     src/coffice/sidebar/ into python/coffice/ (single source of truth, so
#     the code inside the extension is exactly the tested package code);
#   * generates icons/coffice.png with a tiny pure-Python PNG writer when the
#     icon is missing (no image toolchain dependency).
#
# Usage: bash extension/build.sh          (from anywhere)
# Output: dist/Coffice.oxt
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXT="$ROOT/extension"
OUT="$ROOT/dist/Coffice.oxt"

"${PYTHON:-python3}" - "$EXT" "$OUT" <<'PYCODE'
import os
import struct
import sys
import zipfile
import zlib
from pathlib import Path

ext, out = Path(sys.argv[1]), Path(sys.argv[2])


def generate_icon(path: Path) -> None:
    """Write a 32x32 RGBA PNG: blue rounded square with a white 'C'."""
    size = 32
    px = [[(0, 0, 0, 0)] * size for _ in range(size)]
    for y in range(size):
        for x in range(size):
            # rounded square (radius ~6) in brand blue
            dx = max(6 - x, 0, x - (size - 7))
            dy = max(6 - y, 0, y - (size - 7))
            if dx * dx + dy * dy <= 36:
                px[y][x] = (45, 90, 158, 255)  # #2D5A9E
            elif 0 < x < size - 1 and 0 < y < size - 1:
                px[y][x] = (45, 90, 158, 255)
    # white "C" made of three bars, 6px thick
    for y in range(8, 24):
        for x in range(8, 14):
            if 8 <= y <= 13 or 18 <= y <= 23:  # top + bottom bar
                px[y][x] = (255, 255, 255, 255)
            elif 8 <= x <= 13 and 8 <= y <= 23:  # left bar
                px[y][x] = (255, 255, 255, 255)
    raw = b"".join(
        b"\x00" + b"".join(struct.pack("4B", *px[y][x]) for x in range(size))
        for y in range(size)
    )

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


icon = ext / "icons" / "coffice.png"
if not icon.exists():
    generate_icon(icon)

# -- sync the shared contract/doc-commands into the extension package -------
pkg_dir = ext / "python" / "coffice"
pkg_dir.mkdir(parents=True, exist_ok=True)
for name in ("contract.py", "doc_commands.py"):
    source = ext.parent / "src" / "coffice" / "sidebar" / name
    target = pkg_dir / name
    header = (
        "# NOTE: generated by extension/build.sh from src/coffice/sidebar/%s -- "
        "do not edit in place.\n" % name
    )
    body = source.read_text(encoding="utf-8")
    if name == "doc_commands.py":
        # The shipped package is flat (`coffice`, not `coffice.sidebar`), so
        # rewrite the intra-package import to the shipped layout.
        body = body.replace(
            "from coffice.sidebar.contract import DOC_COMMANDS",
            "from coffice.contract import DOC_COMMANDS",
        )
    target.write_text(header + body, encoding="utf-8")

# -- assemble the .oxt ------------------------------------------------------
files = [
    "description.xml",
    "description/description.txt",
    "description/title.txt",
    "META-INF/manifest.xml",
    "Sidebar.xcu",
    "Factories.xcu",
    "ProtocolHandler.xcu",
    "Addons.xcu",
    "icons/coffice.png",
    "python/coffice_panel.py",
    "python/coffice/__init__.py",
    "python/coffice/contract.py",
    "python/coffice/doc_commands.py",
]
missing = [f for f in files if not (ext / f).exists()]
if missing:
    sys.exit("Missing files in extension/: " + ", ".join(missing))

out.parent.mkdir(parents=True, exist_ok=True)
if out.exists():
    out.unlink()
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
    for f in files:
        zf.write(ext / f, f)
print("Built", out)
with zipfile.ZipFile(out) as zf:
    for name in zf.namelist():
        print("  ", name)
PYCODE
