"""Smoke test: create a sample .docx, write text, read outline, see the redline.

Gated on LibreOffice/PyUNO being available; skips cleanly otherwise.
"""

from __future__ import annotations

import pytest

from coffice.core.document import Document
from coffice.core.lo_manager import LO_UNAVAILABLE

pytestmark = pytest.mark.skipif(LO_UNAVAILABLE, reason="LibreOffice/PyUNO not available")


def test_smoke_docx_roundtrip(desktop, tmp_path) -> None:
    doc = Document.create(desktop)
    doc.insert_text(0, "Coffice Smoke Report\n", style="Heading 1")
    doc.insert_text("end", "Generated by the smoke test.\n")
    doc.enable_track_changes()
    doc.insert_text("end", "This line is a tracked insertion.\n")
    doc.set_page_layout({"margins": {"top": 15, "bottom": 15, "left": 20, "right": 20}})

    path = str(tmp_path / "smoke.docx")
    doc.save(path)
    doc.close()

    reopened = Document.open(desktop, path)
    assert reopened.get_text()
    assert reopened.get_outline()[0]["level"] == 1
    redlines = reopened.get_redlines()
    assert any(r["type"] == "Insert" for r in redlines)
    assert "tracked insertion" in "".join(r["text"] for r in redlines)
    reopened.close()
