"""Coffice sidebar shell package, shipped inside the .oxt.

``contract.py`` and ``doc_commands.py`` are generated by ``extension/build.sh``
from the single source of truth in ``src/coffice/sidebar/`` -- do not edit the
copies in this directory by hand.
"""
